export const HTTP_INVALID_CSRF_TOKEN = 419;
export const HTTP_UNPROCESSABLE_ENTITY = 422;
export const HTTP_UNAUTHORIZED = 401;
export const HTTP_CONFLICT = 409;
export const HTTP_MULTI_STATUS = 207;
